spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    url: jdbc:mysql://134.175.96.21:3306/test?useUnicode=true&characterEncoding=utf-8
    username: root
    password: Woshiqin1991.
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: rabbitmq-hello
  rabbitmq:
    host: localhost
    port: 5672
    username: qin
    password: 123456
    publisher-confirms: true
    virtual-host: /
  redis:
    host: 134.175.96.21
    port: 6379
  logging:
    config: classpath:logback-spring.xml
mybatis:
  mapper-locations: classpath:**/mapping/*.xml
  type-aliases-package: com.example.springbootdemo.pojo

server:
  port: 8091
